### ISSUE TITLE
Not works

### ISSUE THREAD

**Issue by artemhorbenko** [sasmeee/igdl#2]
Hey, looks like it doesn't work. It shows download_link, but when I visited it said "This download token is invalid."

**Comment by sasmeee** [comment]
Thank you for bringing up the issue you mentioned. I'd like to offer some guidance to help you troubleshoot the problem and resolve it effectively.

1. **Check the Link**: To start, please verify the link you are attempting to access. It's possible that the link might be incomplete or has expired. Ensure that the link is correctly copied and pasted into your browser's address bar.

2. **Character Integrity**: Make sure that the link has not been altered in any way. Sometimes, extra characters or spaces can inadvertently be included when copying and pasting. Ensure the link is clean and complete.

3. **Expiration**: These downloadable links have expiration time because they are related to temporary content. Regenerating the downloadable link is recommended.

Your patience and attention to these details will greatly assist in resolving the issue you're facing. If you have any more questions or encounter any other challenges, please don't hesitate to get in touch. We're here to help.
